// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Player struct {
	User     *string   `json:"user"`
	Cash     *int      `json:"cash"`
	Seat     *int      `json:"seat"`
	Position *string   `json:"position"`
	Cards    []*string `json:"cards"`
}

type User struct {
	ID     *string `json:"id"`
	Email  *string `json:"email"`
	UserID *string `json:"userId"`
}

type UserInput struct {
	Email  *string `json:"email"`
	UserID *string `json:"userId"`
}
